// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Database.DB {
	public partial class Limit {
		public int Id { get; set; }
		public int ProductId { get; set; }
		public int? LimitValue { get; set; }
		public int? RangeCapacity { get; set; }

		public virtual Product Product { get; set; }
	}
}