// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Database.DB {
	public partial class Product {
		public Product() {
			Limits = new HashSet<Limit>();
		}

		public int Id { get; set; }
		public string Name { get; set; }

		public virtual ICollection<Limit> Limits { get; set; }
	}
}