// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Database.DB {
	public partial class ShopDistribution {
		public int ShopId { get; set; }
		public int ProductId { get; set; }
		public int LimitId { get; set; }
		public decimal? Percentage { get; set; }
	}
}